#!/bin/bash

sxhkd &
#conky -q &  # Disabled because using new widget with same options
nitrogen --restore &
#polybar -c ~/.config/polybar/config.ini & 
xsetroot -cursor_name left_ptr &
picom --config ~/.config/picom/picom.conf &
/usr/libexec/xdg-desktop-portal-gtk &
dunst -conf ~/.config/dunst/dunstrc &
cairo-dock -f &
polybar -c ~/.config/eww/modules/bar/polybar-air.ini & # Is fix stacking for eww, see faq 1
eww open bar &

bspc monitor -d 1 2 3 4 5 6

bspc config normal_border_color "#504945"
bspc config active_border_color "#504945"
bspc config focused_border_color "#ebdbb2"
bspc config presel_feedback_color "#504945"

bspc config border_width 1
bspc config window_gap 11

bspc config split_ratio 0.52

bspc config focus_follows_pointer true
bspc config pointer_modifier super

bspc config borderless_monocle true
bspc config gapless_monocle true
