#!/bin/bash

sxhkd &
nitrogen --restore &
polybar -c /home/sophragoz/.config/polybar/config.ini &
xsetroot -cursor_name left_ptr &
picom --config /home/sophragoz/.config/picom/picom.conf &
/usr/libexec/xdg-desktop-portal-gtk &

#bspc rule -a

bspc monitor -d 1 2 3 4 5 6

bspc config border_width 0
bspc config window_gap 11

bspc config split_ratio 0.52

bspc config focus_follows_pointer true
bspc config pointer_modifier super

bspc config borderless_monocle true
bspc config gapless_monocle true
